### ISSUE TITLE
Congratulations and questions

### ISSUE THREAD

**Issue by frederikhors** [bkonkle/nakago#16]
You are making my dream come true with this framework (again, after caster).

Two things are driving me crazy:

1. use a transaction between two different services, for example:

  - before edit an episode check if the show is in a locked state (just an example)

  - use a transaction in service code without knowing (in that service/usecase layer) what DB I'm using (postgresql or others: for example InMemory fake DB)

1. switch the persistence type at runtime (and I saw that you are doing this in the dependency injection document (although it is very complicated to understand reading it the first time).

I did not find these in the examples/async-graphql dir. Am I wrong?

Thanks in advance as usual: you're very great!

**Comment by frederikhors** [comment]
I have summarized the two big problems in the README of this repository: https://github.com/frederikhors/rust-clean-architecture-with-db-transactions.

Solving them would be a dream for me.

**Comment by bkonkle** [comment]
My son's health issues and my day job have definitely kept me busy lately. Sorry I've been slow to reply here and on the Caster repo. :sweat_smile: Hopefully I'll be able to keep up more effectively as things settle back down to normal.

**Comment by bkonkle** [comment]
I ended up having a busy weekend with my son and with US taxes. :sweat_smile: I'm planning on getting back to this project this week if possible, though.

**Comment by bkonkle** [comment]
I'm working on integration tests here: https://github.com/bkonkle/nakago/pull/18

Once I get that in place, I'll take a look at transactions and runtime switching and see if I can work them into the example.

**Comment by bkonkle** [comment]
Okay, for issue #1 

I tried to go down the road of creating trait wrappers for SeaOrm's `DatabaseConnection` and `DatabaseTransaction`, so that you could start a transaction in the Resolver and simply pass it in to the `create`, `update`, and `delete` methods to make them act against the transaction rather than the connection directly, like this:

```rs
/// A `TransactConnection` is a wrapper around a database connection that allows for transactional
/// queries.
#[async_trait]
pub trait TransactConnection: Send + Sync {
    /// Begin a new transaction
    async fn begin(&self) -> Result<Box<dyn Transaction>>;
}

#[async_trait]
impl TransactConnection for DatabaseConnection {
    async fn begin(&self) -> Result<Box<dyn Transaction>> {
        let tx = sea_orm::TransactionTrait::begin(self).await?;
        Ok(Box::new(tx))
    }
}

/// A `Transaction` is a generic database transaciton.
#[async_trait]
pub trait Transaction: Send + Sync {
    /// Commit a transaction
    async fn commit(&self) -> Result<()>;

    /// Rollback a transaction
    async fn rollback(&self) -> Result<()>;
}

#[async_trait]
impl Transaction for DatabaseTransaction {
    async fn commit(&self) -> Result<()> {
        self.commit().await
    }

    async fn rollback(&self) -> Result<()> {
        self.rollback().await
    }
}
```

Unfortunately, I wasn't able to find a way to get a `Box<dyn Transaction>` to behave as a `C: ConnectionTrait` as required by the constraint in SeaOrm's `ActiveModelTrait` here:

```rs
    async fn update<'a, C>(self, db: &'a C) -> Result<<Self::Entity as EntityTrait>::Model, DbErr>
    where
        <Self::Entity as EntityTrait>::Model: IntoActiveModel<Self>,
        Self: ActiveModelBehavior + 'a,
        C: ConnectionTrait,
    {
        let am = ActiveModelBehavior::before_save(self, db, false).await?;
        let model: <Self::Entity as EntityTrait>::Model = Self::Entity::update(am).exec(db).await?;
        Self::after_save(model, db, false).await
    }
```

With that in mind I think I would abandon the idea of fully dynamic typing here, and instead go with application-level enums that become a thin wrapper around whatever underlying crates you want to work with in your project:

```rs
use sea_orm::DatabaseConnection;

use crate::utils::connections::InMemoryTransaction;

pub enum Connection {
    SeaOrm(DatabaseConnection),
    InMemory(InMemoryConnection),
}

pub enum Transaction {
    SeaOrm(DatabaseTransaction),
    InMemory(InMemoryTransaction),
}

impl Transaction {
    pub async fn begin(connection: &Connection) -> Result<Transaction> {
        match connection {
            Connection::SeaOrm(conn) => {
                let tx = conn.begin().await?;
                Ok(Transaction::SeaOrm(tx))
            }
            Connection::InMemory(conn) => {
                let tx = conn.begin().await?;
                Ok(Transaction::InMemory(tx))
            }
        }
    }

    pub async fn commit() -> Result<()> {
        match self {
            Transaction::SeaOrm(tx) => tx.commit().await,
            Transaction::InMemory(tx) => tx.commit().await,
        }
    }

    pub async fn rollback() -> Result<()> {
        match self {
            Transaction::SeaOrm(tx) => tx.rollback().await,
            Transaction::InMemory(tx) => tx.rollback().await,
        }
    }
}
```

With this approach, you would inject an `Arc<Connection>` with either your SeaOrm or In-Memory connection (with In-Memory being a custom utility or one from another crate entirely) into your dependency injection container (or your Async-GraphQL data layer). When you wanted to use it, you would retrieve your `Arc<Connection>` and call `Transaction::begin(connection)` to generate a new `Transaction` enum instance. You could then pass this into your service/repository/whatever you want to call it, and it could then destructure the enum to get at the actual `DatabaseConnection` or `InMemoryConnection` inside, and use it to execute the operation within the context of the transaction.

This wouldn't work in a fully-generic library situation where you want others to be able to dynamically add new `Transaction` implementations without altering the original code, but it would work fine in an application where you know which crates you're going to support. Making things entirely dynamic so that you don't need an enumeration of possible connection/transaction types would take a lot more effort, I think. :sweat_smile:

**Comment by bkonkle** [comment]
I'll definitely be working on improving the documentation in the weeks ahead. I want to create a `cqrs-es` implementation, and then start adding in some helpful tools to `nakago` for things like CQRS, GraphQL, SeaOrm (and maybe tools for SQLx and Diesel also?), and other libraries in the ecosystem. Ultimately, I want `nakago` to become my one-stop-shop for all the libraries I'll work with in future projects, with the dependency injection system tying everything together.

**Comment by bkonkle** [comment]
Okay, so has all this been helpful? :grinning:

**Comment by bkonkle** [comment]
I've made a lot of progress towards making this a more usable and comprehensive framework, but I still have a ways to go. I don't have any other ORM that I want to use besides SeaOrm right now, and I don't think I'm ready to implement generic database access including a wrapper around transactions yet until I have some good use cases in my own projects to forge a usable abstraction based on.

I **have** dramatically improved the documentation, however, and I have a tutorial and a simple generator to make it easier to get started: https://nakago.dev/docs/tutorial

I'm going to close this ticket for now. I'll be continuing to improve Nakago, and hopefully I'll be able to focus on it more heavily in the future when I have a production project based on it. Thanks for your interest!
